--
-- PostgreSQL database dump
--

\restrict bWkyZ1DgSZyDgU5JD1eUmKsFzg7lMwR8jvgIj4fvqTas1NmfW8lX2o6Zzn5uybV

-- Dumped from database version 15.15
-- Dumped by pg_dump version 15.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apartment; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.apartment (
    area double precision,
    floor integer,
    houseid integer NOT NULL,
    apartmentstatus character varying(255),
    building character varying(255),
    type character varying(255),
    apartment_number character varying(255),
    status character varying(255),
    CONSTRAINT apartment_status_check CHECK (((status)::text = ANY (ARRAY[('EMPTY'::character varying)::text, ('OCCUPIED'::character varying)::text, ('MAINTENANCE'::character varying)::text])))
);


ALTER TABLE public.apartment OWNER TO myuser;

--
-- Name: apartment_houseid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.apartment ALTER COLUMN houseid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apartment_houseid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.fee (
    feeid integer NOT NULL,
    unitprice numeric(10,2),
    billingcycle character varying(50),
    unit character varying(50),
    feename character varying(255) NOT NULL,
    description text,
    id integer NOT NULL,
    is_mandatory boolean
);


ALTER TABLE public.fee OWNER TO myuser;

--
-- Name: fee_feeid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

CREATE SEQUENCE public.fee_feeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fee_feeid_seq OWNER TO myuser;

--
-- Name: fee_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.fee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.invoice (
    duedate date,
    houseid integer,
    invoiceid integer NOT NULL,
    month integer,
    totalamount numeric(12,2) DEFAULT 0.00,
    year integer,
    status character varying(50) DEFAULT 'unpaid'::character varying
);


ALTER TABLE public.invoice OWNER TO myuser;

--
-- Name: invoice_invoiceid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.invoice ALTER COLUMN invoiceid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_invoiceid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoicedetail; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.invoicedetail (
    amount numeric(12,2),
    feeid integer,
    invoiceid integer,
    paymentid integer NOT NULL,
    quantity double precision
);


ALTER TABLE public.invoicedetail OWNER TO myuser;

--
-- Name: invoicedetail_paymentid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.invoicedetail ALTER COLUMN paymentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicedetail_paymentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.payment (
    amountpaid numeric(12,2),
    invoiceid integer,
    paymentid integer NOT NULL,
    paymentdate timestamp(6) with time zone,
    paymentmethod character varying(100),
    transactionstatus character varying(100),
    onlinetransactionid character varying(255)
);


ALTER TABLE public.payment OWNER TO myuser;

--
-- Name: payment_paymentid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.payment ALTER COLUMN paymentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_paymentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refreshtoken; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.refreshtoken (
    accountid integer,
    expiry_date timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    token character varying(255) NOT NULL
);


ALTER TABLE public.refreshtoken OWNER TO myuser;

--
-- Name: refreshtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.refreshtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refreshtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: request; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.request (
    requestid integer NOT NULL,
    adminresponse text,
    content text,
    createddate timestamp(6) without time zone,
    resolveddate timestamp(6) without time zone,
    status character varying(50),
    title character varying(255) NOT NULL,
    residentid integer
);


ALTER TABLE public.request OWNER TO myuser;

--
-- Name: request_requestid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.request ALTER COLUMN requestid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_requestid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resident; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.resident (
    dob date,
    houseid integer,
    residentid integer NOT NULL,
    address character varying(255),
    cccd character varying(255),
    email character varying(255),
    name character varying(255),
    phonenumber character varying(20),
    state character varying(20),
    enddate date,
    note text,
    startdate date,
    avatar character varying(255),
    is_host boolean,
    relationship character varying(255)
);


ALTER TABLE public.resident OWNER TO myuser;

--
-- Name: resident_residentid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.resident ALTER COLUMN residentid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resident_residentid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: useraccount; Type: TABLE; Schema: public; Owner: myuser
--

CREATE TABLE public.useraccount (
    accountid integer NOT NULL,
    residentid integer,
    password character varying(255),
    role character varying(255),
    email character varying(255)
);


ALTER TABLE public.useraccount OWNER TO myuser;

--
-- Name: useraccount_accountid_seq; Type: SEQUENCE; Schema: public; Owner: myuser
--

ALTER TABLE public.useraccount ALTER COLUMN accountid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.useraccount_accountid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: apartment apartment_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.apartment
    ADD CONSTRAINT apartment_pkey PRIMARY KEY (houseid);


--
-- Name: fee fee_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.fee
    ADD CONSTRAINT fee_pkey PRIMARY KEY (feeid);


--
-- Name: invoice invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT invoice_pkey PRIMARY KEY (invoiceid);


--
-- Name: invoicedetail invoicedetail_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.invoicedetail
    ADD CONSTRAINT invoicedetail_pkey PRIMARY KEY (paymentid);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (paymentid);


--
-- Name: refreshtoken refreshtoken_accountid_key; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT refreshtoken_accountid_key UNIQUE (accountid);


--
-- Name: refreshtoken refreshtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT refreshtoken_pkey PRIMARY KEY (id);


--
-- Name: refreshtoken refreshtoken_token_key; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT refreshtoken_token_key UNIQUE (token);


--
-- Name: request request_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.request
    ADD CONSTRAINT request_pkey PRIMARY KEY (requestid);


--
-- Name: resident resident_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.resident
    ADD CONSTRAINT resident_pkey PRIMARY KEY (residentid);


--
-- Name: useraccount useraccount_pkey; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.useraccount
    ADD CONSTRAINT useraccount_pkey PRIMARY KEY (accountid);


--
-- Name: useraccount useraccount_residentid_key; Type: CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.useraccount
    ADD CONSTRAINT useraccount_residentid_key UNIQUE (residentid);


--
-- Name: request fk1nlfymjs9fwhdlqs2hjsyx1v6; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.request
    ADD CONSTRAINT fk1nlfymjs9fwhdlqs2hjsyx1v6 FOREIGN KEY (residentid) REFERENCES public.resident(residentid);


--
-- Name: useraccount fka27gfq7iwuiidlgqnxtr6ilec; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.useraccount
    ADD CONSTRAINT fka27gfq7iwuiidlgqnxtr6ilec FOREIGN KEY (residentid) REFERENCES public.resident(residentid);


--
-- Name: resident fkb7tgqt83veilvaph07d2c2s7n; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.resident
    ADD CONSTRAINT fkb7tgqt83veilvaph07d2c2s7n FOREIGN KEY (houseid) REFERENCES public.apartment(houseid);


--
-- Name: invoice fkgxrp5wy5okeiq5vvg1h5s3o10; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT fkgxrp5wy5okeiq5vvg1h5s3o10 FOREIGN KEY (houseid) REFERENCES public.apartment(houseid);


--
-- Name: payment fkibd0la95x4ju0tbvjuhqyht5f; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkibd0la95x4ju0tbvjuhqyht5f FOREIGN KEY (invoiceid) REFERENCES public.invoice(invoiceid);


--
-- Name: refreshtoken fkik5jhr0cljjdqionpah51u7jp; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.refreshtoken
    ADD CONSTRAINT fkik5jhr0cljjdqionpah51u7jp FOREIGN KEY (accountid) REFERENCES public.useraccount(accountid);


--
-- Name: invoicedetail fkn9evd4vonsr8lnr31txga20o5; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.invoicedetail
    ADD CONSTRAINT fkn9evd4vonsr8lnr31txga20o5 FOREIGN KEY (feeid) REFERENCES public.fee(feeid);


--
-- Name: invoicedetail fkt0mve2vv8ocb25b2779rqeksr; Type: FK CONSTRAINT; Schema: public; Owner: myuser
--

ALTER TABLE ONLY public.invoicedetail
    ADD CONSTRAINT fkt0mve2vv8ocb25b2779rqeksr FOREIGN KEY (invoiceid) REFERENCES public.invoice(invoiceid);


--
-- PostgreSQL database dump complete
--

\unrestrict bWkyZ1DgSZyDgU5JD1eUmKsFzg7lMwR8jvgIj4fvqTas1NmfW8lX2o6Zzn5uybV

